spring.application.name=RBXbackend
spring.datasource.url=jdbc:postgresql://localhost:5432/rbx_db
spring.datasource.username=yamin
spring.datasource.password=PostgresKebab59

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true